server:
  port: 9527

spring:
  application:
    name: cloud-gateway #以微服务注册进consul或nacos服务列表内
  cloud:
    consul: #配置consul地址
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service                #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由
#            - After=2024-03-12T18:34:30.155954800+08:00[Asia/Shanghai] #断言，时间在2021-01-01T00:00:00+08:00之后的请求进行路由
#            - Cookie=username,zhangsan #断言，cookie中包含username=zhangsan的请求进行路由
#            - Header=X-Request-Id, \d+ #断言，请求头中包含X-Request-Id的请求进行路由 要求为正整数
#            - Host=**.atguigu.com #断言，host为*.atguigu.com的请求进行路由
#            - Method=GET #断言，请求方式为GET的请求进行路由
#            - Query=username, \d+ #断言，请求参数中包含username的请求进行路由 要求为正整数
#            - RemoteAddr=localhost #断言，请求的远程地址为localhost的请求进行路由
#            - My=diamond


        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service                #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由


        - id: pay_routh3 #pay_routh3
          uri: lb://cloud-payment-service                #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/filter/**              # 断言，路径相匹配的进行路由
#            - Path=/XYZ/abc/{segment}              # 断言，路径相匹配的进行路由
          filters:
            - My=atguigu
#            - AddRequestHeader=X-Request-atguigu1,atguiguValue1  # 请求头kv，若一头含有多参则重写一行设置
#            - AddRequestHeader=X-Request-atguigu2,atguiguValue2
#            - RemoveRequestHeader=X-Request-atguigu2  # 移除请求头
#            - SetRequestHeader=sec-fetch-mode, Blue-updatebyzzyy  # 设置请求头
#            - AddRequestParameter=customerId,9527001 # 新增请求参数Parameter：k ，v
#            - RemoveRequestParameter=customerName   # 删除url请求参数customerName，你传递过来也是null
#            - AddResponseHeader=X-Response-atguigu, BlueResponse # 新增请求参数X-Response-atguigu并设值为BlueResponse
#            - SetResponseHeader=Date,2099-11-11 # 设置回应头Date值为2099-11-11
#            - RemoveResponseHeader=Content-Type # 将默认自带Content-Type回应属性删除
#            - PrefixPath=/pay  # 前缀路径
#            - SetPath=/pay/gateway/{segment}  # 设置路径
#            - RedirectTo=302,http://www.baidu.com  # 重定向到百度